languageCode = "en-us"
title = "Don't Spy EU"
logo = "/logo/6.png"
theme = "fmeps"

defaultContentLanguage = 'en'
[languages]
  [languages.it]
    languageName = 'it'
    title = "🇮🇹 Europa Non Spiarci!"
    weight = 2
  [languages.en]
    languageName = 'en'
    title = "Don't Spy EU!"
    weight = 1


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
